### ISSUE TITLE
Add environment variable example to README

### ISSUE THREAD

**Issue by georgeflug** [georgeflug/insomnia-plugin-save-variables#12]
Add information to the readme about how to save a variable from this plugin into an environment variable.

**Comment by cnigh** [comment]
Thanks for your efforts!  This issue made me realize why I wasn't having things work using the plugin.  I kept writing the outputs to environment variables.  

Key note I missed after many times of reading - variables vs environment variables.

**Comment by zfwf** [comment]
Can we actually save variable to environment variables? I thought environment variables can be updated by template tags but they are just resolved to static values before saving the environment, thus won't update when the variable changes. Am I missing something here?

**Comment by r-best** [comment]
> Can we actually save variable to environment variables? I thought environment variables can be updated by template tags but they are just resolved to static values before saving the environment, thus won't update when the variable changes. Am I missing something here?

It took me a bit to figure this out, as far as I can tell we can't actually save to *environment variables* (i.e. Insomnia's Base Environment and Sub-Environments)
This plugin uses a call to `context.store.setItem()`, which is a separate local storage only viewable by the plugin that uses it, according to the [Insomnia Docs](https://docs.insomnia.rest/insomnia/context-object-reference#contextstore), which is I assume why this plugin has a template tag for reading variables as well (reads them back from that local storage, not from env vars)

Insomnia exposes a [`getEnvironmentVariable()`](https://github.com/Kong/insomnia/blob/4a30e4f284885ed003c3448732f6176fdd14ff53/packages/insomnia/src/plugins/context/request.ts#L61C9-L61C9) function in its context for retrieving env vars, but doesn't seem to expose a setter, so I'm not sure if it's even possible for a plugin to actually modify an env var

Frankly this seems like a huge feature gap on Insomnia's side, it's a pretty basic thing they should have so plugins can utilize it
It's been brought up in threads in their repo as well without ever being fixed though, so I don't have too much hope for it, this plugin provides the best alternative

**Comment by georgeflug** [comment]
@r-best is right, the Insomnia plugin API does not provide a way to save data to environment variables. I agree it's a feature gap.

I've got a workaround for this. I forgot what it was but these recent comments inspired me to figure it out again. Simply put, you just have to create an environment variable that references the `Variable` template tag. That lets you get to the saved value using the environment variable syntax.

I've updated the Readme with this info.

**Comment by r-best** [comment]
Clever workaround! I hadn't thought of that, it works like a charm
Great work on this plugin btw @georgeflug, I'll be recommending it to some of my coworkers, we were all pushed to insomnia after postman's recent policy changes and I think this will help their workflows
