### ISSUE TITLE
Variable tag not resolving

### ISSUE THREAD

**Issue by cherlo** [georgeflug/insomnia-plugin-save-variables#15]
I just installed this and it's not working.  Is this compatible with version 2021.4.1 (7/6/2021)?  When I set Variable tag what is supposed to be the Input Type?  Static Value or Environment Variable?  I tried typing in the variable id with Static Value and that didn't work.  And the variable id did not appear in the Environment Variable list.  Or is there supposed to be another input type?  I can see the variable set in the All Variables tag so the Save Variable tag appears to be working.

**Comment by georgeflug** [comment]
It is working for me on version 2021.4.1. When using the Variable tag, there is no option for Static Value or Environment Variable. The only thing you have to enter is the variable name. Do you by any chance have another plugin installed that has a Variable tag? If not, can you send a screenshot of the Variable tag screen?

**Comment by georgeflug** [comment]
I see what you mean by Static Value now. Yes it should be static value. Can you send screenshots of the Save Variable tag and the Variable tag?

**Comment by cherlo** [comment]
I changed the Function value to All Variables and then back to Variables, then the value resolved this time.  Maybe, it doesn't resolve if I create the Variable tag before running the request with the Save Variable.  I seem to be doing the right thing.  Just maybe not in the right order.

**Comment by georgeflug** [comment]
Great, yes that is correct, the variable has to be saved at least one time for the value to be resolved.
