### ISSUE TITLE
allow for change variables value manually

### ISSUE THREAD

**Issue by sify21** [georgeflug/insomnia-plugin-save-variables#16]
sometimes I want to modify a variable's value manually instead of update it by sending requests.

**Comment by sify21** [comment]
I created a pull request for this. https://github.com/georgeflug/insomnia-plugin-save-variables/pull/17
Also, during development I find that `install-plugin.sh` is not working correctly.
1. `cd $MY_PLUGIN_DIR` should be quoted to avoid white spaces. 
2. `npm install --only=production` will report `sh: husky: command not found`,  I need to execute `npm set-script prepare ''` beforehand.
3. Even if the script executes successfully, the plugin can't be loaded because npm installs a newer version of `esprima`. I need to install the plugin from insomnia plugin hub and replace `dist` directory manually.

**Comment by georgeflug** [comment]
Thanks for the pull request! I'll take a look when I have time and would love to merge this in, probably before the end of the week.

**Comment by georgeflug** [comment]
I have committed some changes to fix the problems with `install-plugin.sh` and added some comments to the pull request.

**Comment by georgeflug** [comment]
Thanks again for the suggestion and the pull request. I have merged this, made a few tweaks, and published it as version 2.0.2
