### ISSUE TITLE
Deleted Saved Variable

### ISSUE THREAD

**Issue by Splitix** [georgeflug/insomnia-plugin-save-variables#22]
Would be a nice quality of life feature to be able to delete a saved variable that I could use on a DELETE API call. Currently when viewing all variables I'm seeing variables I'm no longer using. 

Not sure how to remove those.

**Comment by georgeflug** [comment]
I like that idea. Thanks for submitting it. I'm thinking there could be a DeleteVariable header (similar to the SaveVariable header) that would delete the variable after the request. Optionally it would only do this if the status code of the response matches the desired outcome.

I don't have the bandwidth at the moment but I can add this in before the end of September.

**Comment by Splitix** [comment]
> Optionally it would only do this if the status code of the response matches the desired outcome.

That would be an awesome addition. Thanks for adding this. Such a great plugin.

**Comment by georgeflug** [comment]
Well I didn't get this in by the end of September but it's coming soon. Stay tuned.

**Comment by georgeflug** [comment]
I'm happy to announce that Version 3.1.0 is published with this feature.
