### ISSUE TITLE
Support saving value from XML response

### ISSUE THREAD

**Issue by johnpaulwelsh** [georgeflug/insomnia-plugin-save-variables#23]
Excellent plugin. I'd like the ability to save a variable taken from an XML response using XPath notation.

**Comment by georgeflug** [comment]
Thanks for the comment. I agree, that's a natural next step for this plugin. I'm not sure when I'll get to it but I'll keep this issue open until the feature is added.

**Comment by georgeflug** [comment]
This has been added in the latest version, 3.3.0
