### ISSUE TITLE
The plugin simply doesnt work for me at all...

### ISSUE THREAD

**Issue by SkyDev125** [georgeflug/insomnia-plugin-save-variables#24]
I have no idea what to do, I've followed exactly how to do it... I've tried everything, it saves the value and shows in "all variables" but it doesn't give me the value in the variable when I call for it.. I have no idea

**Comment by georgeflug** [comment]
I'm not sure but some hopefully we can figure it out with some more info. Can you please do the following:
1. Provide the version of Insomnia, version of the plugin, and which operating system you are on?
2. Try sending the payload below to echo.zuplo.io which is an endpoint that will echo back whatever you send to it.
3. Attach screenshots of the All Variables result and the request/result from the echo server.

Payload for echo.zuplo.io (content-type: application/json):
```
{
	"value": "{your-variable-goes-here}"
}
```

**Comment by SkyDev125** [comment]
nevermind, its working now... I had to fully uninstall insomnia for some reason. thank you!
