### ISSUE TITLE
Is it possible to add two variables together?

### ISSUE THREAD

**Issue by SkyDev125** [georgeflug/insomnia-plugin-save-variables#25]
I've been trying to find a way to add 2 variables together, or to add one variable with some extra text. etc... and I cant find how to do so in insomnia or with your plugin. is that even possible?

**Comment by georgeflug** [comment]
Are you talking about string concatenation? That's possible like this:
![image](https://user-images.githubusercontent.com/13152990/196841037-f62075f6-ed70-4f40-af9e-feaebff29e8f.png)

There's no functional composition in Insomnia though so you can't do nested variables, pass variables to other tags, or anything like that.

**Comment by SkyDev125** [comment]
Yeah, mainly I was intending on getting the data from my request's query parameters. So I could use the parameter of a chained request on the next one

Like
Request Step 1 - (html base with prompts)
Request Step 2 - (html from step 1 + new html base with prompts)
.
.
. 
Step 9 same thing.

But I've found it to be impossible to do with the research I've done. Insomnia provides one that lets you get the data from one of your parameters in the current request's query you have open... But for me that is deemed useless. As id need to be able to select parameters from different request's queries... Not the current open one

**Comment by georgeflug** [comment]
If I understand correctly it sounds like you want to save a variable from the _request_ side of a request, but you cannot do that because this plugin can only save a variable from the _response_ side of a request. Is that right?

**Comment by SkyDev125** [comment]
Yes, I think you got it right

**Comment by georgeflug** [comment]
Ok great. I'll leave this open as a feature request. I'm planning to expand this plugin to have more ways to extract variables, including more data types (xml mainly - see #23) and also more sources such as status codes, request data, etc.

**Comment by SkyDev125** [comment]
Alright that's great, thank you ;3. Cause my solution was very cumbersome, where I had to use 2 functions, one to send the data, one to retrieve the data I sent, and then another to send the data to a different step, etc.

This could be very useful :3 and reduce the size of my test unit very quickly.

**Comment by georgeflug** [comment]
You can now save values from the request body in the latest version 4.0.1.
