### ISSUE TITLE
Get a variable in an Array

### ISSUE THREAD

**Issue by zergy83** [georgeflug/insomnia-plugin-save-variables#28]
Hello,
On a json response containing an array of element, I use jsonpath regexp to get an array:
$..[?(@.myField="good")].myId
This returns an array of "myId" compatible with the filter:
[
"11111",
"22222",
"33333",
"44444"
]
However, I would like to use the first one of this array. Would it be possible to add this option/function to your great plugin please? 
thanks

**Comment by georgeflug** [comment]
Would this work?
```
$..[?(@.myField="good")].myId[0]
```
If not can you paste an example of the json input so that I can have a better understanding of what is being queried?

**Comment by zergy83** [comment]
Hello, thanks for repliying.
No ironicaly, it does return the first character of each string like:
{1,
2,
3
}
.

Here is the model of my response (an array of object with fields and subfields):
[
{
"myField":"Good",
"myId": "zazaza-12345-zazaza",
"expiration": "2023-01-17"
}
{
"myField":"Bad",
"myId: "zouzouzouz-12345-zozozozo",
"expiration": "2023-01-20"
}
]

**Comment by georgeflug** [comment]
Gotcha, I understand. I could add some non-standard stuff to the JSONPath implementation, or add an extra option that does another layer of filtering. But the best option is to add support for JMESPath which is much more powerful and can handle that situation, plus many more. I'll keep support for both - you'll still be able to use JSONPath if you are more familiar with that, and can switch to JMESPath in situations where that's not good enough.

e.g. If you go to https://jmespath.org/ you can test out queries. With your data, the following query would work: `[?myField == 'Good'].myId | [0]`

**Comment by zergy83** [comment]
Hello, george, yes thanks you very much. Adding support of JMESPath is a great idea. Its works well for my sample and we could then integrate our insomnia tests to our java project. Thank you very much, I hope to see this feature in your next release. best of luck to you

**Comment by georgeflug** [comment]
JMESPath is now available in the latest version 4.0.1

**Comment by zergy83** [comment]
Hello, thank you for the implementation. I'll look into it on monday. sincerely
