### ISSUE TITLE
Response Body XPath returns tag name and tag value

### ISSUE THREAD

**Issue by Gdebroux79** [georgeflug/insomnia-plugin-save-variables#29]
**Current behavior**
Hello,
When we Save the value of a data present in a body
/html//input[@name='_csrf']/@value

The value stored in the variable contains the tag name in place to have only the value.
stored in my value:  value="88642be7-0fa8-4ff2-80f3-4f6601612ca6"

**Expected behavior**
Expected value stored:  88642be7-0fa8-4ff2-80f3-4f6601612ca6

Is it something I used in an incorrect way?

Insomnia Version: 2023.1.0
Plugin version: 4.0.2

Regards,
Glenn

**Comment by georgeflug** [comment]
This plugin uses a standard xpath parser so you can use any online XPath testers to try out the XPath and verify the correct syntax. Here's a good one: https://codebeautify.org/Xpath-Tester. In this case you should be able to get the value you want by wrapping your XPath with `string()`:
```
string(/html//input[@name='_csrf']/@value)
```

Hope it helps :)

**Comment by Gdebroux79** [comment]
Thanks a lot,
It worked
