### ISSUE TITLE
Dependency xmldom fails security scan

### ISSUE THREAD

**Issue by availity-droo** [georgeflug/insomnia-plugin-save-variables#32]
We would like to use this plugin within our organization; however, all opensource projects must pass a security scan to be approved.  

The `xmldom` package contains known High and Critical vulnerabilities (https://security.snyk.io/package/npm/xmldom/0.6.0) and has been superseded by `@xmldom/xmldom` as the package maintainer could no longer post updates to the `xmldom` package.  See https://github.com/xmldom/xmldom/issues/271

I have opened a PR (https://github.com/georgeflug/insomnia-plugin-save-variables/pull/31) which resolves this issue and allows this plugin to pass the security scan.

**Comment by georgeflug** [comment]
Thanks for the PR! I have merged it.
